import enum


class RiskLevel(str, enum.Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    SUSPICIOUS = "SUSPICIOUS"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RiskSignalType(str, enum.Enum):
    UPFRONT_PAYMENT = "UPFRONT_PAYMENT"
    RECRUITER_DOMAIN_MISMATCH = "RECRUITER_DOMAIN_MISMATCH"
    SUSPICIOUS_HIRING_PROCESS = "SUSPICIOUS_HIRING_PROCESS"
    UNREALISTIC_COMPENSATION = "UNREALISTIC_COMPENSATION"
    HIGH_PRESSURE_LANGUAGE = "HIGH_PRESSURE_LANGUAGE"
    GUARANTEED_SELECTION = "GUARANTEED_SELECTION"
    HISTORICAL_REPORTS = "HISTORICAL_REPORTS"
    SUSPICIOUS_APPLICATION_URL = "SUSPICIOUS_APPLICATION_URL"
    SENSITIVE_INFORMATION_REQUEST = "SENSITIVE_INFORMATION_REQUEST"
    POSSIBLE_IMPERSONATION = "POSSIBLE_IMPERSONATION"
    SIMILAR_HISTORICAL_RISK_FOUND = "SIMILAR_HISTORICAL_RISK_FOUND"
    OFF_PLATFORM_COMMUNICATION = "OFF_PLATFORM_COMMUNICATION"
    SUSPICIOUS_PAYMENT_METHOD = "SUSPICIOUS_PAYMENT_METHOD"
    UNREALISTIC_PROMISES = "UNREALISTIC_PROMISES"

    # Positive signals
    VERIFIED_COMPANY_DOMAIN = "VERIFIED_COMPANY_DOMAIN"
    VERIFIED_OFFICIAL_JOB = "VERIFIED_OFFICIAL_JOB"
    VERIFIED_RECRUITER = "VERIFIED_RECRUITER"


SIGNAL_SCORES = {
    RiskSignalType.UPFRONT_PAYMENT.value: 30,
    RiskSignalType.RECRUITER_DOMAIN_MISMATCH.value: 20,
    RiskSignalType.SUSPICIOUS_HIRING_PROCESS.value: 15,
    RiskSignalType.UNREALISTIC_COMPENSATION.value: 15,
    RiskSignalType.HIGH_PRESSURE_LANGUAGE.value: 10,
    RiskSignalType.GUARANTEED_SELECTION.value: 10,
    RiskSignalType.HISTORICAL_REPORTS.value: 20,
    RiskSignalType.SUSPICIOUS_APPLICATION_URL.value: 20,
    RiskSignalType.SENSITIVE_INFORMATION_REQUEST.value: 15,
    RiskSignalType.POSSIBLE_IMPERSONATION.value: 25,
    RiskSignalType.SIMILAR_HISTORICAL_RISK_FOUND.value: 15,
    RiskSignalType.OFF_PLATFORM_COMMUNICATION.value: 20,
    RiskSignalType.SUSPICIOUS_PAYMENT_METHOD.value: 25,
    RiskSignalType.UNREALISTIC_PROMISES.value: 15,
    RiskSignalType.VERIFIED_COMPANY_DOMAIN.value: -15,
    RiskSignalType.VERIFIED_OFFICIAL_JOB.value: -25,
    RiskSignalType.VERIFIED_RECRUITER.value: -15,
}


def get_signal_score(signal_type: str) -> int:
    return SIGNAL_SCORES.get(signal_type, 0)


def get_risk_level(score: int) -> RiskLevel:
    if score <= 20:
        return RiskLevel.LOW
    elif score <= 40:
        return RiskLevel.MODERATE
    elif score <= 60:
        return RiskLevel.SUSPICIOUS
    elif score <= 80:
        return RiskLevel.HIGH
    else:
        return RiskLevel.CRITICAL
