import { ArrowLeft, LockKeyhole, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { LogoMark } from "./Home";

export default function Privacy() {
  return (
    <div className="legal-shell">
      <header className="site-header legal-header"><Link className="brand" href="/"><LogoMark /><span>Hire<span>Shield</span></span></Link><Link className="back-link" href="/"><ArrowLeft size={15} /> Back to home</Link></header>
      <main className="legal-main"><div className="legal-kicker"><LockKeyhole size={15} /> Privacy / last updated April 2026</div><h1>Privacy, in plain language.</h1><p className="legal-lede">HireShield is designed to help you review uncertain recruitment opportunities without turning your job search into a data product.</p><div className="legal-notice"><ShieldCheck size={18} /><p><strong>Short version:</strong> use the service to analyze material you have the right to share. We use it to return your requested analysis, improve reliability, and keep the service safe. We do not publish your documents or sell personal information.</p></div><div className="legal-body"><h2>What you can submit</h2><p>You may submit a job posting, recruitment message, offer letter, or related text for analysis. Please remove information that is not needed for the check, such as government identification numbers, bank details, passwords, or unrelated personal records.</p><h2>How submitted material is used</h2><p>Submitted material is processed to produce an analysis of recruitment warning signs and practical next steps. It may be retained for a limited period to support your session, prevent abuse, troubleshoot failures, and improve the service. We do not use your document to create a public profile about you.</p><h2>What a result means</h2><p>HireShield results are risk indicators based on the information provided. They are not definitive accusations, legal advice, employment advice, or a substitute for verifying an opportunity through independent channels.</p><h2>Information we may collect</h2><p>We may receive account or contact details you provide, the content you submit, technical information needed to operate the site, and basic event logs used for security and reliability. We aim to collect only what is reasonably necessary for these purposes.</p><h2>Third parties</h2><p>We may use service providers for hosting, storage, security, and analysis infrastructure. They are expected to process information only to provide services to HireShield and under appropriate confidentiality and security commitments.</p><h2>Your choices</h2><p>You can ask what personal information we hold, request correction or deletion where applicable, or contact us with a privacy question. Email <a href="mailto:privacy@hireshield.example">privacy@hireshield.example</a> and include enough context for us to respond without sending sensitive material unnecessarily.</p><h2>Changes to this policy</h2><p>When this policy changes, we will update the date above and explain material changes through the product where appropriate.</p></div></main><footer className="site-footer legal-footer"><div className="container footer-bottom"><span>© 2026 HireShield</span><span>Results are indicators, not definitive accusations.</span><Link href="/terms">Terms & Conditions</Link></div></footer>
    </div>
  );
}
