import { ArrowLeft, FileSearch, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { LogoMark } from "./Home";

export default function Terms() {
  return (
    <div className="legal-shell">
      <header className="site-header legal-header"><Link className="brand" href="/"><LogoMark /><span>Hire<span>Shield</span></span></Link><Link className="back-link" href="/"><ArrowLeft size={15} /> Back to home</Link></header>
      <main className="legal-main"><div className="legal-kicker"><FileSearch size={15} /> Terms & Conditions / last updated April 2026</div><h1>Use HireShield with care.</h1><p className="legal-lede">These terms describe the boundaries of a tool built to support careful decisions about recruitment opportunities.</p><div className="legal-notice"><ShieldCheck size={18} /><p><strong>The essential point:</strong> HireShield provides informational risk indicators. It does not determine whether a person, company, message, or job opportunity is fraudulent or legitimate.</p></div><div className="legal-body"><h2>Using the service</h2><p>You may use HireShield for lawful, personal, or organizational purposes. You are responsible for ensuring that you have the right to submit any content you provide and that the content does not include information you are prohibited from sharing.</p><h2>Do not rely on a score alone</h2><p>Analysis can be incomplete, incorrect, or based on misleading source material. Verify job opportunities through the employer’s official website and trusted contact channels. Do not send money, passwords, identity documents, or sensitive financial information solely because HireShield did not flag a warning sign.</p><h2>Prohibited use</h2><p>Do not use the service to violate another person’s privacy, upload malware, attempt unauthorized access, interfere with the service, or submit material in a way that breaks applicable law or an agreement you have with another party.</p><h2>Intellectual property</h2><p>HireShield, its visual identity, software, and original content belong to HireShield or its licensors. You retain rights in material you submit, subject to the permissions needed for us to provide the service.</p><h2>Availability and changes</h2><p>We may update, pause, or discontinue parts of the service as it develops. We will make reasonable efforts to keep the product understandable and useful, but we do not promise uninterrupted availability or that every risk will be detected.</p><h2>Disclaimer</h2><p>The service is provided for general information and decision support. It is not legal, financial, employment, cybersecurity, or investigative advice. To the extent permitted by law, HireShield is not responsible for a decision you make based only on an analysis result.</p><h2>Contact</h2><p>Questions about these terms can be sent to <a href="mailto:support@hireshield.example">support@hireshield.example</a>. For privacy requests, see our <Link href="/privacy">Privacy Policy</Link>.</p></div></main><footer className="site-footer legal-footer"><div className="container footer-bottom"><span>© 2026 HireShield</span><span>Results are indicators, not definitive accusations.</span><Link href="/privacy">Privacy Policy</Link></div></footer>
    </div>
  );
}
